version: '3'
services:

  bot:
    build: ./bot
    env_file:
      - env/bot.env
    volumes: 
      - ./bot:/app
      - ./bot/logs:/app/logs
    command: [ "python", "./manage.py", "runbot"]

  redis:
    image: redis:latest
    env_file:
      - env/redis.env
    ports:
      - "6379:6379"
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:latest
    env_file:
      - env/postgres.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-volume:
  redis-data: